import { initializeApp } from "https://www.gstatic.com/firebasejs/9.22.1/firebase-app.js";
import { getAuth, signInWithEmailAndPassword } from "https://www.gstatic.com/firebasejs/9.22.1/firebase-auth.js";

// Firebase configuration
const firebaseConfig = {
    apiKey: "AIzaSyCGgM4xfImc3zUGZ3deAKrT1nnj1eqIJpM",
    authDomain: "hospitallogin-1c882.firebaseapp.com",
    projectId: "hospitallogin-1c882",
    storageBucket: "hospitallogin-1c882.firebasestorage.app",
    messagingSenderId: "118156012652",
    appId: "1:118156012652:web:11ca6afd81dbba17e6fc49"
  };


// Initialize Firebase
const app = initializeApp(firebaseConfig);
const auth = getAuth(app);


// Example Hospital Data
const hospitalData = [
    "Ramlal Kundanlal Orthopaedic Hospital",
    "Panchsheel Hospital Pvt Ltd",
    "Monga Medical Centre",
    "Sehgal Neo Hospital",
    "Kesar Hospital",
    "Indraprastha Apollo Hospital",
    "Sir Ganga Ram Hospital",
    "Max Super Specialty Hospital",
    "Shanti Mukand Hospital",
    "Rs Grover Memorial Hospital",
    "Mahajan Eye Centre",
    "RG STONE UROLOGY AND LAPAROSCOPY HOSPITAL",
    "Indian Spinal injuries Centre",
    "Khandelwal Hospital and Urology Centre",
    "Bajaj Eye Care Centre",
    "Shreya Eye Centre",
    "Kosmos Superspeciality Hospital ™",
    "Sama Hospital",
    "Venkateshwar Hospital",
    "Roopchand Hospital",
    "Centre For Sight Ashok Vihar",
    "Dr. Gupta Nursing Home And Hospital",
    "Eye Q Super Specialty Eye Hospital Shalimarbagh",
    "Shree Aggarsain International Hospital",
    "Dr Bajaj Eye Hospital",
    "Saroj Super Speciality Hospital",
    "Dharamshila Hospital and Research Centre",
    "Indus Valley Hospitals",
    "MANIPAL HOSPITAL(HCMCT)",
    "Shri Moolchand Kharaiti Ram Hospital",
    "Centre For Sight Dwarka",
    "Tirath Ram Shah Hospital",
    "Sri Balaji Action Medical Institute",
    "Spectra Eye",
    "Indraprastha Apollo Hospital",
    "Jaipur Golden Hospital",
    "Kukreja Hospital And Heart Centre",
    "East Delhi Medical Centre, Shahdara, Delhi-32",
    "Sir Ganga Ram Hospital",
    "Sharp Sight Centre (East)",
    "Max super speciality Hospital (Patparganj)",
    "Handa Nursing Home",
    "Makkar Medical Centr",
    "Max Super Specialty East Block Saket (Devki Devi)",
    "Centre For Sight Preet Vihar",
    "Jain Hospital New Delhi",
    "SHARP SIGHT CENTRE",
    "Walia Nursing And Maternity Home",
    "Bensups Hospital (New Delhi)",
    "Jeewan Hospital And Nursing Home",
    "Jeewan Mala Hospital Pvt Ltd",
    "Primus Super Speciality Hospital",
    "Metro Hospitals And Cancer Institute",
    "SEHGAL NURSING HOME( AZADPUR)",
    "Lion Kidney Hospital And Urology Research Institute",
    "Narang Eye Institute Laser And Retina Centre",
    "Neera Eye Centre And Laser Vision",
    "Visitech Eye Centre",
    "RLKC HOSPITAL METRO HEART INSTITUTE",
    "Drishti Eye Laser Centre",
    "Max Super Speciality Hospital West Block",
    "Mata Roop Rani Maggo And Mahindru Hospital",
    "BM Gupta Nursing Home Pvt Ltd Uttam Nagar",
    "MAHARAJA AGRASEN HOSPITAL",
    "Kailash Nursing Home Pvt Ltd",
    "Cygnus Sonia Hospital (A Unit Of Altius Healthcare Pvt Ltd)",
    "Durga Hospital Pvt Ltd",
    "HOLY CHILD NURSING HOME",
    "Jeevan Jyoti Clinic And Nursing Home",
    "Lotus Hospital (Harinagar)",
    "Divya Prastha Hospital",
    "Dr BL Kapur Memorial Hospital",
    "Dr Kapur The Healing Touch Eye Centre",
    "Fortis La Femme",
    "Khanna Hospital",
    "Mohan Eye Institute",
    "Genesis Hospital Pvt Ltd",
    "SUNDER LAL JAIN CHARITABLE HOSPITAL",
    "K.K Surgical And Maternity Centre( Loni Road)",
    "Rajiv Gandhi Cancer Institute And Research Centre",
    "Bharti Eye Foundation",
    "Khanna Eye Centre Delhi",
    "Vision Eye Hospital(Delhi)",
    "Aashlok Fortis Hospital",
    "Bhagat Chandra Hospital",
    "Vinayak Hospital Delhi",
    "Eden Hospital Pvt Ltd",
    "Fortis Escorts Heart Institute",
    "Metro Hospital And Heart Institute (New Delhi)",
    "Hemraj Jain Hospital And Maternity Home",
    "Adiva Hospitals",
    "Satya Bhama Hospital",
    "Janki Hospital",
    "VISION EYE CENTRE",
    "Max Smart Super Speiality Hospital (Mandir Marg)",
    "SURAKSHA EYE SURGERY CENTRE",
    "Balaji Hospital",
    "Shubham Hospital",
    "SIR GANGA RAM KOLMET HOSPITAL",
    "SAI RETINA FOUNDATION",
    "Jain Eye Hospital And Laser Centre",
    "Tarak Hospital",
    "Gandhi Hospital",
    "ICLINIX Advanced Eye Care",
    "Chopra Eye Hospital",
    "Kalra Hospital SRCNC Pvt Ltd",
    "NETRAYATAN GROVER CENTRE FOR EYE CARE AND INFERTILITY",
    "Agrawal Eye Insitute (New Delhi)",
    "St Stephen Hospital",
    "Holy Family Hospital",
    "BALI NURSING HOME",
    "Jeewan Hospital And Nursing Home Pvt Ltd (Jeewan Nagar)",
    "Hi Tech Eye Centre",
    "Bhagat Hospital",
    "JOY NURSING HOME",
    "SHRI RAM SINGH HOSPITAL AND HEART INSTITUTE",
    "CENTRE FOR SIGHT ROHINI",
    "Centre For Sight Rajouri",
    "PT. GLM SHARMA AMEDA HOSPITAL",
    "SANJEEVAN HOSPITAL",
    "SURYA HOSPITAL (PROP.MISRA HOSPITAL NURSING HOME PVT.LTD)",
    "Sunrise Hospital",
    "RG Stone Urology And Laproscopy Hospital Preet Vihar",
    "Rana Eye Centre",
    "Swasthik Hospital (A Unit Of Sushom Health Care Pvt.Ltd)",
    "DR AGGARWALS EYE CLINIC",
    "ASHA HOSPITAL",
    "SANJEEVAN SURGICAL CENTRE",
    "Maharaja Agrasen Hospital Dwarka",
    "Navjeewan Medical Centre (Delhi)",
    "M.M. Eyetech Institute",
    "Sarthak Medical Centre",
    "Rockland Hospitals Ltd",
    "Sawan Neelu Angel Nursing Home",
    "Pentamed Hospital",
    "Mahindru Hospital",
    "Life Line Hospital Dwarka",
    "Talwar Medical Centre",
    "Shishu Sadan Multispeciality Hospital",
    "Eye 7 Chaudhary Eye Centre",
    "Pushpanjali Hospital And Trauma Centre",
    "Apollo Spectra Hospitals (Apollo Speciality Hospitals Private Ltd) (Karolba",
    "Rathi Hospital",
    "Dr Shroff charity eye hospital",
    "Amar Leela Hospital Pvt. Ltd.",
    "Ardent Ganpati Hospital",
    "Cygnus MLS Super Speciality Hospital",
    "Delhi Eye Centre",
    "Apollo Spectra Hospitals",
    "Fortis C-Doc Healthcare Ltd",
    "Delhi Hospital & Temple Nursing Home",
    "AS Kidney Hospital & Stone Centre Pvt. Ltd",
    "Institute of Brain and Spine",
    "Apollo Cradle - For Women & Children (A Unit Of Apollo Speciality Hospitals Pvt Ltd)",
    "Medanta The Medicity",
    "Ahuja Eye Centre",
    "MD Eye Care And Laser Centre",
    "Tomar Multispeciality Hospital",
    "Irene Hospital",
    "Mahajan Hospital",
    "Vikas Hospital",
    "UK Nursing Home",
    "Dr Reena Janana & Surgical Hospital",
    "Suman Super Speciality Hospital",
    "Swasthik Hospital",
    "SHRI DHANVANTRI HOSPITAL",
    "Konarc Multispeciality Hospital",
    "Nestiva Hospital",
    "Ishan Hospital",
    "Delhi Eye Care",
    "Galaxy Hospital",
    "Eye 7 Hospitals Pvt Ltd",
    "Park Hospital",
    "HOPE Oncology Care Clinic",
    "Rajiv Gandhi Cancer Institute and Research Centre A Venture with National Chest Institute",
    "Apollo Spectra Hospitals Nehru Enclave",
    "Bharti Eye Hospital",
    "Centre For Sight Vikas Puri",
    "Foresight Eye Clinic",
    "Fortis Hospital Shalimar Bagh",
    "Kailash Eye Care (Unit Of Kailash Nursing Home )",
    "Kartik Nursing Home And Urology Centre",
    "Max Super Speciality Hospital (Shalimar Bagh)",
    "SCI International Hospital (Isis Hospital Pvt Ltd)",
    "Surya Kiran Hospital Pvt Ltd",
    "Universal Hospital",
    "Vasan Eye Care(Janakpuri)",
    "Vimhans (Vidyasagar Institute Of Mental Health And Neuro Science)",
    "Visitech Eye Centre",
    "Visitech Eye Centre Jasola Vihar",
    "Aakash Healthcare Super Speciality Hospital",
    "Rosewood Hospital",
    "Sinha Hospital",
    "Action Cancer Hospital",
    "Ayushman Hospital",
    "Sir Ganga Ram City Hospital",
    "New Vision Eye Centre",
    "Madhukar Rainbow Childrens Medicare Pvt Ltd",
    "I Create Hospital",
    "Aster Eye Care",
    "Diyos Mens Hospital",
    "Dr. Gupta Nursing Home And Hospital",
    "Eye Q Super Specialty Eye Hospital Shalimarbagh",
    "Shree Aggarsain International Hospital",
    "Dr Bajaj Eye Hospital",
    "Saroj Super Speciality Hospital",
    "Dharamshila Hospital and Research Centre",
    "Indus Valley Hospitals",
    "MANIPAL HOSPITAL(HCMCT)",
    "Shri Moolchand Kharaiti Ram Hospital",
    "Centre For Sight Dwarka",
    "Tirath Ram Shah Hospital",
    "Sri Balaji Action Medical Institute",
    "Spectra Eye",
    "Indraprastha Apollo Hospital",
    "Jaipur Golden Hospital",
    "Kukreja Hospital And Heart Centre",
    "East Delhi Medical Centre, Shahdara, Delhi-32",
    "Sir Ganga Ram Hospital",
    "Sharp Sight Centre (East)",
    "Max super speciality Hospital (Patparganj)",
    "Handa Nursing Home",
    "Makkar Medical Centr",
    "Max Super Specialty East Block Saket (Devki Devi)",
    "Centre For Sight Preet Vihar",
    "Rg Stone Urology And Laproscopy Hospital",
    "Goyal Hospital & Urology Centre",
    "Goyal Eye Institute",
    "Fortis Flt Lt Rajan Dhall Hospital",
    "RG Stone Urology And Laproscopy Hospital",
    "DEEPAK MEMORIAL HOSPITAL AND MEDICAL RESEARCH CENTRE",
    "Save Sight Centre",
    "Sant Parmanand Hospital",
    "Delhi Heart And Lung Institute",
    "Banarasidass Institute Of Medical Science",
    "Jeewan Nursing Homeand Hospital",
    "Sukhda Hospital",
    "Amit Nursing Home",
    "Aakash Hospital",
    "Pushpanjali Medical Centre",
    "MGS Hospital",
    "Shree Jeewan Hospital",
    "Venu Eye Institute And Research Centre",
    "Bhagwati Hospital (Unit Of Sarvodya Health Foundation)",
    "Chaudhary Eye Centre And Laser Vision",
    "Khetarpal Nursing Home",
    "Mata Chanan Devi Hospital",
    "Centre For Sight Safdarjung",
    "Bhagwan Mahavir Hospital",
    "Khetarpal Hospital",
    "Shroff Eye Centre",
    "CENTRE FOR SIGHT DEFENCE ENCLAVE",
    "National Heart Institute",
    "Rockland Hospital",
    "Jeevan Jyoti Hospital(New Delhi)",
    "Dr Patnaiks Laser Eye Institute",
    "Aarogya Hospital",
    "BHATIA GLOBAL HOSPITAL AND ENDOSURGERY INSTITUTE",
    "Pushpawati Singhania Research Institute",
    "Medfirst Ent Centre",
    "Vision Eye Centre",
    "Kapoor Medical Centre(Delhi)",
    "Navjyoti Eye Centre",
    "Bansal Hospital",
    "Max Healthcare Institute Ltd ( Pancheel Park)",
    "MAX HEALTHCARE INSTITUTE PVT LTD",
    "Dashmesh Hospital",
    "Central Hospital (Delhi)",
    "Batra Hospital And Medical Research Centre",
    "Sodhi Nursing Home And Ent Hospital",
    "Dr Sushma Jindal Hospital Delhi",
    "Nazar Kanwar Surana Hospital",
    "Ganesh Ortho Trauma And Medical Centre (Delhi)",
    "SUKHMANI HOSPITAL",
    "AYUSHMAN HOSPITAL",
];

// Populate Dropdown Dynamically
document.addEventListener('DOMContentLoaded', () => {
    const dropdown = document.getElementById('hospital-dropdown');

    // Add hospital options
    hospitalData.forEach(hospital => {
        const option = document.createElement('option');
        option.value = hospital;
        option.textContent = hospital;
        dropdown.appendChild(option);
    });

    // Initialize Select2 for the dropdown if available
    if (typeof $ !== 'undefined' && typeof $.fn.select2 !== 'undefined') {
        $(dropdown).select2({
            placeholder: "Select a hospital",
            allowClear: true
        });
    }
});

// Handle Hospital Login Form Submission
document.getElementById('hospital-login-form').addEventListener('submit', (e) => {
    e.preventDefault();
    const selectedHospital = document.getElementById('hospital-dropdown').value;
    const email = document.getElementById('email').value.trim();
    const password = document.getElementById('password').value.trim();

    if (!selectedHospital) {
        alert('Please select a hospital.');
        return;
    }

    if (!email || !password) {
        alert('Please fill in all fields.');
        return;
    }

    // Firebase Authentication
    signInWithEmailAndPassword(auth, email, password)
        .then(userCredential => {
            console.log("Login successful for:", userCredential.user.email);
            alert(`Welcome, ${selectedHospital}!`);
            window.location.href = 'hospital-dashboard.html'; // Adjust to your dashboard page
        })
        .catch(error => {
            console.error("Login error:", error.code, error.message);
            alert("Login failed. Please check your credentials.");
        });
});

